name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME_UNDERSCORE: vrcx-insights

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Install mingw
        run: sudo apt-get install -y mingw-w64
      - name: Install x86_64-pc-windows-gnu
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install x86_64-pc-windows-msvc
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --verbose --release --target x86_64-pc-windows-gnu --manifest-path .github/workflows/Cargo.toml
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}.exe
